import { PARTS_PROV_COLLECTION_TOOLS } from './collection.js';
import { PARTS_PROV_QUERY_TOOLS } from './query.js';
import { PARTS_PROV_AUDIT_TOOLS } from './audit.js';

export const PARTS_PROV_TOOLS = [
	...PARTS_PROV_COLLECTION_TOOLS,
	...PARTS_PROV_QUERY_TOOLS,
	...PARTS_PROV_AUDIT_TOOLS
];

export { PARTS_PROV_COLLECTION_TOOLS, PARTS_PROV_QUERY_TOOLS, PARTS_PROV_AUDIT_TOOLS };
