import { CLINICAL_COLLECTION_TOOLS } from './collection.js';
import { CLINICAL_NOTE_TOOLS } from './notes.js';
import { CLINICAL_CONSENT_TOOLS } from './consent.js';
import { CLINICAL_BILLING_TOOLS } from './billing.js';
import { CLINICAL_QUERY_TOOLS } from './query.js';
import { CLINICAL_AUDIT_TOOLS } from './audit.js';
import { CLINICAL_LNC_TOOLS } from './lnc.js';
import { CLINICAL_DCL_TOOLS } from './dcl.js';

export const CLINICAL_SCRIBE_TOOLS = [
	...CLINICAL_COLLECTION_TOOLS,
	...CLINICAL_NOTE_TOOLS,
	...CLINICAL_CONSENT_TOOLS,
	...CLINICAL_BILLING_TOOLS,
	...CLINICAL_QUERY_TOOLS,
	...CLINICAL_AUDIT_TOOLS,
	...CLINICAL_LNC_TOOLS,
	...CLINICAL_DCL_TOOLS
];

export {
	CLINICAL_COLLECTION_TOOLS,
	CLINICAL_NOTE_TOOLS,
	CLINICAL_CONSENT_TOOLS,
	CLINICAL_BILLING_TOOLS,
	CLINICAL_QUERY_TOOLS,
	CLINICAL_AUDIT_TOOLS,
	CLINICAL_LNC_TOOLS,
	CLINICAL_DCL_TOOLS
};
