import type { MCPTool } from '@tressellate/core/config';
import { mintNFT } from '@tressellate/core';
import { requireConfigField, createAuditSubmitter } from '@tressellate/core/helpers';
import type { ClinicalScribeConfig } from '../config.js';

const requireNoteCollectionId = requireConfigField<ClinicalScribeConfig>(
	'clinicalNoteCollectionId', 'Clinical note collection ID not configured. Set HEDERA_CLINICAL_NOTE_COLLECTION_ID or use clinical_create_note_collection first.'
);

const submitClinicalAudit = createAuditSubmitter<ClinicalScribeConfig>(
	(config) => config.clinicalAuditTopicId, 'clinical-scribe'
);

export const CLINICAL_NOTE_TOOLS: MCPTool<ClinicalScribeConfig>[] = [
	{
		name: 'clinical_attest_note',
		description: 'Attests a clinical note by minting an NFT. The note content stays in the EHR; this records an immutable attestation with content hash, codes, and clinician signature on-ledger. Supports SOAP, H&P, progress, discharge, procedure, consultation, and referral note formats.',
		inputSchema: {
			type: 'object',
			properties: {
				encounterId: { type: 'string', description: 'Unique encounter/visit identifier' },
				patientHash: { type: 'string', description: 'Patient identifier (hashed for privacy)' },
				clinicianId: { type: 'string', description: 'Attesting clinician account ID' },
				noteFormat: { type: 'string', description: 'Note format (SOAP, HISTORY_PHYSICAL, PROGRESS, DISCHARGE, PROCEDURE, CONSULTATION, REFERRAL)' },
				specialty: { type: 'string', description: 'Medical specialty (GENERAL, CARDIOLOGY, ONCOLOGY, PSYCHIATRY, PAEDIATRICS, SURGERY, DERMATOLOGY, NEUROLOGY, ORTHOPAEDICS, EMERGENCY)' },
				encounterType: { type: 'string', description: 'Encounter type (IN_PERSON, TELEHEALTH, HOME_VISIT, EMERGENCY, FOLLOW_UP)' },
				contentHash: { type: 'string', description: 'SHA-256 hash of the full note content stored in the EHR' },
				icdCodes: { type: 'array', items: { type: 'string' }, description: 'ICD-10 diagnosis codes' },
				cptCodes: { type: 'array', items: { type: 'string' }, description: 'CPT procedure codes' },
				language: { type: 'string', description: 'Encounter language (ISO 639-1)', default: 'en' },
				aiGenerated: { type: 'boolean', description: 'Whether the note was AI-generated by ambient scribe', default: false },
				encounterDate: { type: 'string', description: 'When the encounter occurred (ISO 8601)' }
			},
			required: ['encounterId', 'patientHash', 'clinicianId', 'noteFormat', 'specialty', 'encounterType', 'contentHash', 'icdCodes', 'cptCodes', 'encounterDate']
		},
		implementation: async (args, config) => {
			const collectionId = requireNoteCollectionId(config);
			const metadata = JSON.stringify({
				type: 'CLINICAL_NOTE',
				encounterId: args.encounterId,
				patientHash: args.patientHash,
				clinicianId: args.clinicianId,
				noteFormat: args.noteFormat,
				specialty: args.specialty,
				encounterType: args.encounterType,
				contentHash: args.contentHash,
				icdCodes: args.icdCodes,
				cptCodes: args.cptCodes,
				language: (args.language as string) ?? 'en',
				aiGenerated: (args.aiGenerated as boolean) ?? false,
				clinicianAttested: true,
				encounterDate: args.encounterDate,
				attestedAt: new Date().toISOString()
			});
			const mintResult = await mintNFT(config, collectionId, [metadata]);
			const serialNumber = mintResult.serialNumbers[0];
			await submitClinicalAudit(config, {
				event: 'NOTE_ATTESTED',
				encounterId: args.encounterId,
				noteFormat: args.noteFormat,
				specialty: args.specialty,
				aiGenerated: args.aiGenerated ?? false,
				serialNumber,
				mintTxId: mintResult.transactionId
			});
			return {
				success: true, serialNumber,
				transactionId: mintResult.transactionId,
				encounterId: args.encounterId,
				noteFormat: args.noteFormat,
				message: `Clinical note attested on-ledger. Serial #${serialNumber} — immutable proof of attestation.`
			};
		}
	},
	{
		name: 'clinical_record_provenance',
		description: 'Records a provenance event for a clinical note (created, edited, reviewed, attested, amended, addendum). Tracks the full chain of who touched the note and when.',
		inputSchema: {
			type: 'object',
			properties: {
				noteRef: { type: 'string', description: 'Clinical note serial number reference' },
				action: { type: 'string', description: 'Action performed (CREATED, EDITED, REVIEWED, ATTESTED, AMENDED, ADDENDUM)' },
				actorId: { type: 'string', description: 'Who performed the action' },
				actorRole: { type: 'string', description: 'Actor role (AI_SCRIBE, PHYSICIAN, NURSE, CODER, SPECIALIST)' },
				contentHash: { type: 'string', description: 'Hash of the note content at this point in time' },
				changeSummary: { type: 'string', description: 'What changed (for edits/amendments)' }
			},
			required: ['noteRef', 'action', 'actorId', 'actorRole', 'contentHash']
		},
		implementation: async (args, config) => {
			const collectionId = requireNoteCollectionId(config);
			const metadata = JSON.stringify({
				type: 'NOTE_PROVENANCE',
				noteRef: args.noteRef,
				action: args.action,
				actorId: args.actorId,
				actorRole: args.actorRole,
				contentHash: args.contentHash,
				changeSummary: args.changeSummary,
				timestamp: new Date().toISOString()
			});
			const mintResult = await mintNFT(config, collectionId, [metadata]);
			const serialNumber = mintResult.serialNumbers[0];
			await submitClinicalAudit(config, {
				event: 'PROVENANCE_RECORDED',
				noteRef: args.noteRef,
				action: args.action,
				actorId: args.actorId,
				actorRole: args.actorRole,
				serialNumber,
				mintTxId: mintResult.transactionId
			});
			return {
				success: true, serialNumber,
				transactionId: mintResult.transactionId,
				noteRef: args.noteRef,
				action: args.action
			};
		}
	}
];
